name: CICD Pipeline for BankingAPP

on:
  push:
    branches: [ "main" ]

jobs:
  maven_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean verify
      
  docker_build:
    runs-on: ubuntu-latest
    needs: maven_build
    
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Use 'secrets' to store the username
        password: ${{ secrets.DOCKER_PASSWORD }}  # 'DOCKER_PASSWORD' should be in secrets for security reasons
    - name: Docker Build & Push
      run: |
        docker build -t pavan539/bankapp:${{ github.sha }} .  
        docker push pavan539/bankapp:${{ github.sha }}
        docker run -d -p 8080:8080 pavan539/bankapp:${{ github.sha }}
        docker ps  # Show running containers to verify it's up
