name: CICD Pipeline for BankingApp

on:
  push:
    branches: [ "main" ]

jobs:
  maven_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean verify

  docker_build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Docker image
      run: |
        docker build -t pavan539/bankapp:${{ github.sha }} .
        
    - name: Push Docker image to Docker Hub
      run: |
        docker push pavan539/bankapp:${{ github.sha }}
